### ISSUE TITLE
QA Toolkit - Inspections-Schedule Tab - Add a New Button within Grids to Open a New QA-2 Inspection

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#295] opened 2016-12-12 18:22 UTC
### On the Inspection Tab-Schedule Tab,  add a new Button to the grids that will launch a new QA-2 report

   1.  Add a new button 'QA-2' to the (2) existing grids. **When the user clicks the _QA-2 Button_, the system opens a new QA-2 form with a pre-existing association to the corresponding project.**
   2.  Update the existing _"New"_ button to the _"QA1"_ button (currently used elsewhere in the toolkit)

![image](https://cloud.githubusercontent.com/assets/23661339/21111089/eff0a9fa-c06d-11e6-930b-079d03ac92ce.png)

_Tracking Note: this issue was originally requested as **No. 3.15 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment] 2017-02-01 14:54
Implemented in dev

**Comment by linsentp** [comment] 2017-02-01 19:32
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment] 2017-03-06 14:56
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment] 2017-03-10 15:16
Button looks good and functions properly but in the Staging environment the schedule grid expands beyond the right edge of the page.  This does not occur in the Dev. environment.

**Comment by vijme** [comment] 2017-03-10 15:25
Tad, Will it be possible to post a screenshot? Looks good to me in IE and Chrome in STAGING.

**Comment by Tad-Daniel** [comment] 2017-03-10 15:36
Here is what I am seeing

![offset](https://cloud.githubusercontent.com/assets/7913678/23801204/4ed9bef8-057d-11e7-9e03-2ebd730a6bf2.png)

**Comment by vijme** [comment] 2017-03-10 16:22
@Tad-Daniel : I am unable to replicate the issue. However, I tried a minor css update to STAGING. Could you please check if issue is still there. Thanks.

**Comment by Tad-Daniel** [comment] 2017-03-10 17:54
I am still seeing the issue and I am replicating it on my phone.  It looks to only be effecting the schedule grid and not the lower grids on the page.  It does not effect the projects not started or the inspections on hold

**Comment by Tad-Daniel** [comment] 2017-03-10 17:58
Here is the lower sections view.

![lower](https://cloud.githubusercontent.com/assets/7913678/23806797/2788d00a-0591-11e7-84c0-c0aea32452ea.png)

**Comment by Tad-Daniel** [comment] 2017-03-10 18:02
Looks like the Project column is awful wide in staging

**Comment by vijme** [comment] 2017-03-10 19:58
The problem appears when browser width is less to the extent that scroll bar appears. The schedule table has added columns that cannot be further reduced. I tried giving fixed width to project, but thats messing up the whole table. I may need more time to address this.

**Comment by slmessier** [comment] 2017-03-10 20:03
Tad - please advise as whether to:
1. exclude this enhancement but otherwise proceed with the rollout to PROD this weekend
OR
2. postpone the push to PROD until this enhancement is fully resolved.

Thank you!

**Comment by vijme** [comment] 2017-03-10 20:15
If agreeable,  would exclude this enhancement for the weekends release.

**Comment by vijme** [comment] 2017-03-10 20:22
Issue 299 (pending MODS and QA) would be excluded, this enhancement 295 will be included.

**Comment by Tad-Daniel** [comment] 2017-03-10 20:48
Exclude this enhancement but proceed with rollout.

Is it possible the issue is with the staging environment and it would be OK in prod

Thanks



Tad Daniel - Quality Assurance Program, Team Leader
Office of Environmental Design
410-365-0164
Sent from my phone


-------- Original message --------

**Comment by vijme** [comment] 2017-03-10 20:50
You may be right. I expect it not to happen in production and I intend to check it in tonights release. If it looks good in production, then we might have it, otherwise i will remove .

**Comment by Tad-Daniel** [comment] 2017-03-10 21:00
Sounds good, if it helps some of the column headers could be shortened.

Pending QA -> Pend QA
Pending Mods -> Pend Mods
Days Remaining -> Days

**Comment by vijme** [comment] 2017-03-11 02:56
Ok. Updated column headers.

**Comment by Tad-Daniel** [comment] 2017-03-13 15:17
Looks good in production

**Comment by Tad-Daniel** [comment] 2017-03-16 13:58
Looks good

**Closed by Tad-Daniel** 2017-03-16 13:58 UTC
Labels: enhancement, QA Toolkit, Ready for Production, Ready for Staging, Task 11 - Subtask 3 - General UI
