### ISSUE TITLE
QA Toolkit - Reconcile Existing Bug: Add New Project Milestone - Date Selector

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#348] opened 2017-08-15 19:59 UTC
**Reconcile Existing Bug: Add New Project Milestone - Date Selector. Date selection for “add new milestone” in the project record is not working correctly:**

Required Enhancement Specification(s): 
1. Research & Reconcile
2. Previously recorded GitHub #59 (related) 

_Tracking Note: this issue was originally requested as **No. 14.D within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343 of this repository._

**Comment by vijme** [comment] 2017-08-16 21:13
Fixed in dev.

**Comment by HollySchuelerKCI** [comment] 2017-09-14 19:25
@vijme 
1. Is it possible to have the calendar picker for the date range as noted in the mockup.
2. To keep consistency with elsewhere in the toolkit, can date format be changed to mm/dd/yyyy?

**Comment by vijme** [comment] 2017-09-14 19:34
As far as I checked with the toolkits, date Range actually works like range of dates not specific to a particular year. So any milestone that has a date range recurs for every year henceforth, which is the reason why it cannot be picked from the calendar.  I am not sure if date range is used in QA toolkits, but it is used that way in MDE toolkit. We may need to get clarifications from Tad regarding this.

**Comment by slmessier** [comment] 2017-09-14 20:12
@Tad-Daniel - could you please assess existing date selector functionality and provide direction on:

**1. is date range allowable as day and month format exclusively (MM/DD) as is consistent with MDE toolkit as described by Viji above?
2. is calendar selector functionality required for user input? or is typing text value (without a calendar selector) sufficient?**

**Comment by Tad-Daniel** [comment] 2017-09-15 13:38
The date range should be a full date MM/DD/YYYY
Typing is how we currently use this section but it is the only calendar in the toolkit that does not function properly

**Comment by vijme** [comment] 2017-09-15 15:24
Implemented in dev.

**Comment by HollySchuelerKCI** [comment] 2017-09-15 15:37
This issue has been successfully verified by the project team and confirmed by stakeholders in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment] 2017-10-03 18:39
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment] 2017-10-05 00:21
Works correctly

**Comment by Tad-Daniel** [comment] 2017-10-20 10:02
Item complete

**Closed by Tad-Daniel** 2017-10-20 10:02 UTC
Labels: bug, QA Toolkit, Ready for Production, Ready for Staging, TASK 14 – New Functionality Development
