### ISSUE TITLE
QA Toolkit - Application Error when Merging Projects

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#402] opened 2018-04-14 00:01 UTC
The Merge Projects function is producing an application error message when executing the function on certain projects. Please investigate the source of the issue and identify potential method(s) for resolving.

Tad noted in the meeting held on 4/12 that he is receiving an application error when merging projects. Tad noted that when trying to merge **BA5525266** into **BA5525266R** he receives an error.

Tad believes that this new error is not the same as previously reported in GitHub #340 
- the two do not have the same date or time
- both have inspections
- both projects have different project numbers, but the **_same_** description

### Email Reference
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Friday, April 13, 2018 7:59 AM
To: Scott Messier <Scott.Messier@kci.com>
Subject: Missions critical Bug

As we discussed yesterday the Merge projects function is not working correctly

I get an error when trying to merge BA5525266 into BA5525266R

![image](https://user-images.githubusercontent.com/4098544/38810392-a064ae4a-4154-11e8-8d22-bc31bfbd6890.png)

**Comment by vijme** [comment] 2018-04-23 14:50
It looks like both the projects have a plan sheet with the same name and when trying to merge we need unique names for the plan sheets. The simplest fix would be to change the name of one of the plan sheet. This holds good for impact plates too.  

![image](https://user-images.githubusercontent.com/6668314/39133441-30d03a70-46e2-11e8-860a-1b5d72bf6b36.png)

![image](https://user-images.githubusercontent.com/6668314/39133527-6d94293a-46e2-11e8-94ff-49fa6972574a.png)

@Tad-Daniel, can you please confirm if it works. Once the issue is confirmed, we can move towards  developing a more permanant solution if needed. Thanks.

**Comment by Tad-Daniel** [comment] 2018-04-23 15:29
Yes,

**Comment by vijme** [comment] 2018-05-15 13:47
The Plan sheet name, impact plate name and resources type-name combo are unique to a project. When two projects having same name for plan sheet, impact plate and type-name combo for resources, during merge the source project items will be deleted. 

Issue fixed in dev.

**Comment by HollySchuelerKCI** [comment] 2018-05-16 13:53
This issue has been confirmed by project team in the Development Environment.

**Comment by Tad-Daniel** [comment] 2018-05-16 15:16
I seem to be having an issue.  While there are 300+ project in the system when I go to the merge projects and reset the search field I only see 54.   Looks like it correlates to the project not started checkbox that was added to the project listing grid

**Comment by vijme** [comment] 2018-05-16 15:51
Nice catch. The issue has been fixed. The page may show error if it was already open. Please try to delete cache if page shows error.

**Comment by HollySchuelerKCI** [comment] 2018-05-16 16:00
The issue of the project not started checkbox being selected by default has been corrected. This issue has been confirmed by the project team.

**Comment by Tad-Daniel** [comment] 2018-05-16 16:19
Working correctly in DEV

**Comment by HollySchuelerKCI** [comment] 2018-05-16 16:28
This issue has been confirmed by the stakeholder.

The status of this issue is "Ready for Staging"

**Comment by Tad-Daniel** [comment] 2018-05-17 21:07
Working in staging

**Comment by HollySchuelerKCI** [comment] 2018-05-17 21:10
This issue has been validated by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment] 2018-07-11 13:38
Item completed

**Closed by Tad-Daniel** 2018-07-11 13:38 UTC
Labels: QA Toolkit, Ready for Production, Ready for Staging, Task 17 - On Call Support & Maintenance Yr 4&5, bug
